version: '3.8'

services:
  db:
    image: 'postgres:13-alpine'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pw
    volumes:
      - ./docker/db-init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"